export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// error types
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CHANNELS_LOADING = 'CHANNELS_LOADING';
export const GET_CHANNELS = 'GET_CHANNELS';
export const EMPTY_CHANNELS = 'EMPTY_CHANNELS';
export const SHOW_CHANNEL = 'SHOW_CHANNEL';


export const VIDEOS_LOADING = 'VIDEOS_LOADING';
export const GET_VIDEOS = 'GET_VIDEOS';
export const SHOW_VIDEO = 'SHOW_VIDEO';
export const EMPTY_VIDEO = 'EMPTY_VIDEO';

export const SUBSCRIPTION_LOADING = 'SUBSCRIPTION_LOADING';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const EMPTY_SUBSCRIPTION = 'EMPTY_SUBSCRIPTION';
export const CHANGE_SUBSCRIPTION  = 'CHANGE_SUBSCRIPTION';




